# Generated by Django 3.2.9 on 2021-11-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Prestación de bus',
                'verbose_name_plural': 'Prestaciones de bus',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('code', models.CharField(max_length=40, verbose_name='Código')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('vehicle_type', models.IntegerField(choices=[(1, 'Regular'), (2, 'Pickup'), (3, 'Vehículo Personal')], verbose_name='Tipo')),
                ('status', models.IntegerField(choices=[(1, 'En servicio'), (2, 'Fuera de servicio'), (3, 'Propuesto'), (4, 'Mantenimiento')], verbose_name='Estado')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('kilometers', models.IntegerField(blank=True, null=True, verbose_name='Kilómetros')),
                ('motor_serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de serie del motor')),
                ('chassis_serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de serie del Chasís')),
                ('color', models.CharField(blank=True, max_length=60, null=True, verbose_name='Color')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año')),
                ('insurance_policy', models.CharField(blank=True, max_length=50, null=True, verbose_name='Póliza de seguro')),
                ('insurance_policy_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin de póliza de seguro')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dueño')),
                ('services', models.ManyToManyField(to='transportation.Benefit', verbose_name='Prestaciones ofrecidas')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de asiento',
                'verbose_name_plural': 'Tipos de asiento',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transportation.bus', verbose_name='Bus')),
            ],
            options={
                'verbose_name': 'Disposición en bus',
                'verbose_name_plural': 'Disposición de bus',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Número de piso')),
                ('length', models.PositiveSmallIntegerField(verbose_name='Largo de canvas')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ancho de canvas')),
                ('seats', models.PositiveSmallIntegerField(verbose_name='Número de asientos')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.layout', verbose_name='Diseño de bus')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveSmallIntegerField(default=1, verbose_name='Posición X')),
                ('position_y', models.PositiveSmallIntegerField(default=1, verbose_name='Posición Y')),
                ('width', models.PositiveSmallIntegerField(default=1, verbose_name='Ancho')),
                ('length', models.PositiveSmallIntegerField(default=1, verbose_name='Largo')),
                ('kind', models.CharField(choices=[('seat', 'Asiento'), ('bath', 'Baño'), ('hall', 'Pasillo'), ('stair', 'Escalera'), ('tele', 'Televisión'), ('dispenser', 'Dispensador'), ('space', 'Espacio')], max_length=10, verbose_name='Tipo')),
                ('floor', models.ManyToManyField(related_name='components', to='transportation.Floor', verbose_name='Piso')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_transportation.component_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transportation.component')),
                ('seat_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.seattype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
            },
            bases=('transportation.component',),
        ),
    ]
