# Generated by Django 3.2.9 on 2021-11-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportation.layout', verbose_name='Disposición'),
        ),
        migrations.AddField(
            model_name='seat',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
    ]
