# Generated by Django 3.2.10 on 2021-12-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_alter_floor_layout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='floor',
            new_name='floors',
        ),
    ]
