# Generated by Django 3.2.10 on 2021-12-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_rename_floor_component_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='floors',
        ),
        migrations.AddField(
            model_name='component',
            name='floors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='transportation.floor', verbose_name='Piso'),
        ),
    ]
