# Generated by Django 3.2.9 on 2021-11-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('status', models.IntegerField(choices=[(1, 'Inactivo'), (2, 'Activo'), (3, 'Licencia'), (4, 'Desvinculado')], default=2, verbose_name='Estado')),
                ('contract_type', models.CharField(choices=[('9x3', '9 x 3'), ('3x4', '3 x 4'), ('5x2', '5 x 2')], default='5x2', max_length=10, verbose_name='Tipo de contrato')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('description', models.CharField(max_length=70, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='PersonalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Inactivo'), (2, 'Activo')], default=2, verbose_name='Estado')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.personal', verbose_name='Personal')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.position', verbose_name='Posición')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Desde')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Hasta')),
                ('motive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.motive', verbose_name='Motivo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.personal', verbose_name='Personal')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='motives',
            field=models.ManyToManyField(through='crew.PersonalMotive', to='crew.Motive'),
        ),
        migrations.AddField(
            model_name='personal',
            name='positions',
            field=models.ManyToManyField(through='crew.PersonalPosition', to='crew.Position'),
        ),
    ]
