# Generated by Django 3.2.9 on 2021-11-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_alter_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contratación'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='contract_type',
            field=models.CharField(choices=[('9x3', '9 x 3'), ('10x4', '10 x 4'), ('5x2', '5 x 2')], default='5x2', max_length=10, verbose_name='Tipo de contrato'),
        ),
    ]
