# Generated by Django 3.2.9 on 2021-11-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_auto_20211111_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmotive',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Desde'),
        ),
    ]
