# Generated by Django 3.2.9 on 2021-11-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0005_alter_personalmotive_date_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('date_from', models.DateField(verbose_name='Desde')),
                ('date_to', models.DateField(verbose_name='Hasta')),
                ('status', models.IntegerField(choices=[(1, 'Inactivo'), (2, 'Activo')], default=2, verbose_name='Estado')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
            },
        ),
    ]
