# Generated by Django 3.2.9 on 2021-11-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0007_auto_20211117_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='crew.personal', verbose_name='Personal'),
        ),
    ]
