# Generated by Django 3.2.9 on 2021-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0010_alter_commission_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionlog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
