# Generated by Django 3.2.10 on 2021-12-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0011_alter_commissionlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='contract_type',
            field=models.CharField(choices=[('shift_9x3', '9 x 3'), ('shift_10x4', '10 x 4'), ('shift_5x2', '5 x 2')], default='shift_5x2', max_length=10, verbose_name='Tipo de contrato'),
        ),
    ]
