# Generated by Django 3.2.10 on 2021-12-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0012_alter_personal_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='contract_type',
            field=models.CharField(choices=[('9x3', 'Horario 9x3'), ('10x4', 'Horario 10x4'), ('5x2', 'Horario 5x2')], default='5x2', max_length=10, verbose_name='Tipo de contrato'),
        ),
    ]
