# Generated by Django 4.0.5 on 2022-06-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0016_commissionlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='contract_type',
            field=models.CharField(choices=[('unlimited', 'Indefinite'), ('fixed', 'Plazo fijo')], default='fixed', max_length=10, verbose_name='Tipo de contrato'),
        ),
    ]
