from api.core.views.cash_register import CashRegisterViewSet
from api.core.views.coupon import CouponViewSet
from api.core.views.dashboard import DashboardViewSet
from api.core.views.passenger import PassengerViewSet
from api.core.views.rate_type import RateTypeViewSet
from api.core.views.refund_request import RefundRequestViewSet
from api.core.views.reports import ReportViewSet
from api.core.views.reserved_seat import ReservedSeatsViewSet
from api.core.views.route import RouteViewSet
from api.core.views.sale import SaleViewSet
from api.core.views.service import ServiceViewSet
from api.core.views.stretch_info import StretchInfoViewSet
from api.core.views.ticket import TicketViewSet
from api.core.views.service_message import ServiceMessageViewSet
