# Generated by Django 4.0.5 on 2022-06-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cellphone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de celular'),
        ),
    ]
