# Generated by Django 4.0.5 on 2022-06-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='document_type',
            field=models.CharField(blank=True, choices=[('RUT', 'RUT'), ('DNI', 'DNI'), ('PASSPORT', 'PASSPORT')], default='RUT', max_length=9, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='maternal_last_name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.nationality', verbose_name='Nacionalidad'),
        ),
    ]
