# Generated by Django 4.0.5 on 2022-06-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactweb',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos web'},
        ),
    ]
