# Generated by Django 4.0.5 on 2022-06-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_contactweb_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactweb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
