# Generated by Django 3.2.9 on 2021-11-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('latitude', models.CharField(blank=True, max_length=15, null=True, verbose_name='Latitud')),
                ('longitude', models.CharField(blank=True, max_length=15, null=True, verbose_name='Longitud')),
                ('stop_type', models.CharField(choices=[('terminal', 'Terminal'), ('stop', 'Parada')], default='stop', max_length=9, verbose_name='Tipo de parada')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='locations.region', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Parada de bus',
                'verbose_name_plural': 'Paradas de bus',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('latitude', models.CharField(blank=True, max_length=15, null=True, verbose_name='Latitud')),
                ('longitude', models.CharField(blank=True, max_length=15, null=True, verbose_name='Longitud')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='locations.region', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
