# Generated by Django 3.2.9 on 2021-11-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_branch_busstop_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='locations.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='locations.city', verbose_name='Ciudad'),
        ),
    ]
