# Generated by Django 3.2.10 on 2021-12-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20211129_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Prioridad'),
        ),
    ]
