# Generated by Django 4.0.3 on 2022-04-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_busstop_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distancia desde Santiago'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='time',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo desde Santiago'),
        ),
    ]
