# Generated by Django 4.0.3 on 2022-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_busstop_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='time',
        ),
        migrations.AddField(
            model_name='busstop',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distancia'),
        ),
    ]
