# Generated by Django 4.0.3 on 2022-05-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_remove_busstop_time_busstop_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='duration',
        ),
    ]
