# Generated by Django 3.2.9 on 2021-11-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0007_auto_20211117_1115'),
        ('transportation', '0001_initial'),
        ('locations', '0002_branch_busstop_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ruta maestra',
                'verbose_name_plural': 'Rutas maestras',
            },
        ),
        migrations.CreateModel(
            name='MasterRouteStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='Duración')),
                ('distance', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Distancia')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='Ciudad')),
                ('end_bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_master_routes', to='locations.busstop', verbose_name='Parada de fin')),
                ('master_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterroute', verbose_name='Ruta maestra')),
                ('start_bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_master_routes', to='locations.busstop', verbose_name='Parada de inicio')),
            ],
            options={
                'verbose_name': 'Tramo',
                'verbose_name_plural': 'Tramos',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Pasajeo',
                'verbose_name_plural': 'Pasajeros',
            },
        ),
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('time_start', models.TimeField(verbose_name='Hora de inicio')),
                ('time_end', models.TimeField(verbose_name='Hora de fin')),
            ],
            options={
                'verbose_name': 'Tipo de tarifa',
                'verbose_name_plural': 'Tipos de tarifa',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('master_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterroute', verbose_name='Ruta maestra')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='RouteStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('master_route_stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterroutestretch', verbose_name='Tramo de ruta maestra')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route', verbose_name='Ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('datetime_publish', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('datetime_from', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('datetime_to', models.DateTimeField(verbose_name='Fecha de fin')),
                ('service_type', models.CharField(choices=[('short', 'Corto'), ('large', 'Largo')], max_length=9, verbose_name='Tipo de servicio')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportation.bus', verbose_name='Bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route', verbose_name='Ruta')),
                ('tripulation', models.ManyToManyField(to='crew.Personal', verbose_name='Tripulación')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('normal', 'Normal'), ('virtual', 'Virtual')], max_length=9, verbose_name='Tipo de boleto')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger', verbose_name='Pasajero')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.seattype', verbose_name='Tipo de asiento')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True, verbose_name='Método de pago')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Estado de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado')], max_length=9, verbose_name='Estado')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.personal', verbose_name='Vendedor')),
                ('tickets', models.ManyToManyField(to='core.Ticket', verbose_name='Boletos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='RouteStretchRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ratetype', verbose_name='Tipo de tarifa')),
                ('route_stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.routestretch', verbose_name='Ruta')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.seattype', verbose_name='Tipo de asiento')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.CreateModel(
            name='MasterRouteStretchRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('master_route_stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterroutestretch', verbose_name='Ruta maestra')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.seattype', verbose_name='Tipo de asiento')),
            ],
        ),
    ]
