# Generated by Django 3.2.9 on 2021-11-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_auto_20211129_1553'),
        ('crew', '0008_alter_commission_personal'),
        ('locations', '0003_auto_20211129_1553'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transportation.seat', verbose_name='Asiento'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('pending', 'Pendiente'), ('billed', 'Depositado'), ('blocked', 'Bloqueado')], max_length=9, verbose_name='Estado')),
                ('created', models.DateTimeField(verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.branch', verbose_name='Sucursal')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.personal', verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cashregister'),
        ),
    ]
