# Generated by Django 3.2.9 on 2021-12-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211129_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterroutestretch',
            options={'verbose_name': 'Tramo de ruta maestra', 'verbose_name_plural': 'Tramos de ruta maestra'},
        ),
        migrations.AlterModelOptions(
            name='masterroutestretchrate',
            options={'verbose_name': 'Tarifa de ruta maestra', 'verbose_name_plural': 'Tarifas de ruta maestra'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Pasajero', 'verbose_name_plural': 'Pasajeros'},
        ),
        migrations.AlterModelOptions(
            name='routestretch',
            options={'verbose_name': 'Tramo de ruta', 'verbose_name_plural': 'Tramos de ruta'},
        ),
    ]
