# Generated by Django 3.2.9 on 2021-12-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_masterroutemap'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='masterroutemap',
            constraint=models.UniqueConstraint(fields=('master_route', 'bus_stop'), name='unique bus stop in master route'),
        ),
    ]
