# Generated by Django 3.2.10 on 2021-12-14 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20211129_1553'),
        ('core', '0008_ticket_reserved_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_maps', to='locations.busstop', verbose_name='Paradas')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_maps', to='core.masterroute', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Mapa de ruta',
                'verbose_name_plural': 'Mapas de rutas',
            },
        ),
        migrations.AddConstraint(
            model_name='routemap',
            constraint=models.UniqueConstraint(fields=('route', 'bus_stop'), name='unique bus stop in route'),
        ),
    ]
