# Generated by Django 3.2.10 on 2021-12-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211214_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemap',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_maps', to='core.route', verbose_name='Ruta'),
        ),
    ]
