# Generated by Django 3.2.10 on 2021-12-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0014_auto_20211215_1721'),
        ('core', '0010_alter_routemap_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tripulation',
        ),
        migrations.AddField(
            model_name='service',
            name='assistants',
            field=models.ManyToManyField(related_name='assistants_services', to='crew.Personal', verbose_name='Auxiliares'),
        ),
        migrations.AddField(
            model_name='service',
            name='drivers',
            field=models.ManyToManyField(related_name='drivers_services', to='crew.Personal', verbose_name='Conductores'),
        ),
    ]
