# Generated by Django 3.2.10 on 2021-12-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0014_auto_20211215_1721'),
        ('core', '0011_auto_20211221_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerNationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Nacionalidad del pasajero',
                'verbose_name_plural': 'Nacionalidades de los pasajeros',
            },
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='sex',
        ),
        migrations.AddField(
            model_name='passenger',
            name='document_type',
            field=models.CharField(default='RUT', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='service',
            name='renovation_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses renovación'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.personal', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.passengernationality', verbose_name='Nacionalidad'),
        ),
    ]
