# Generated by Django 3.2.10 on 2022-01-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211223_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passenger_type',
            field=models.CharField(choices=[('child', 'Child'), ('adult', 'Adult')], default='ADULT', max_length=6, verbose_name='Tipo de pasajero'),
        ),
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Servicio Padre'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='one_way_parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticket', verbose_name='Servicio Ida'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_source',
            field=models.CharField(blank=True, choices=[('branch_office', 'Branch office'), ('web', 'Web')], max_length=15, null=True, verbose_name='fuente de compra del boleto'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='document_type',
            field=models.CharField(choices=[('RUT', 'RUT'), ('DNI', 'DNI')], default='RUT', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('one_way', 'One way'), ('return', 'Return')], max_length=9, verbose_name='Tipo de boleto'),
        ),
        migrations.CreateModel(
            name='ServiceDayBlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_service', models.DateTimeField(verbose_name='Fecha de servicio')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_days_blocked', to='core.service')),
            ],
            options={
                'verbose_name': 'Servicio día bloqueado',
                'verbose_name_plural': 'Servicios días bloqueados',
            },
        ),
    ]
