# Generated by Django 3.2.10 on 2022-01-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_auto_20211228_1122'),
        ('core', '0014_reservedseat_reservedseats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservedseat',
            options={'verbose_name': 'Asiento reservado', 'verbose_name_plural': 'Asientos reservados'},
        ),
        migrations.AlterField(
            model_name='reservedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='transportation.seat', verbose_name='Asiento'),
        ),
    ]
