# Generated by Django 3.2.10 on 2022-01-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220110_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('short', 'Corto'), ('large', 'Largo')], max_length=9, verbose_name='Estado de servicio'),
        ),
        migrations.DeleteModel(
            name='ServiceDayBlocked',
        ),
    ]
