# Generated by Django 3.2.10 on 2022-02-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('total_prints', models.IntegerField(verbose_name='Total de impresiones')),
            ],
        ),
        migrations.AddField(
            model_name='cashregister',
            name='total_prints',
            field=models.IntegerField(default=0, verbose_name='Total de impresiones'),
        ),
    ]
