# Generated by Django 3.2.10 on 2022-02-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220206_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Impresora', 'verbose_name_plural': 'Impresoras'},
        ),
        migrations.AddField(
            model_name='cashregister',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.printer', verbose_name='Impresora'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buy_order',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Orden compra'),
        ),
    ]
