# Generated by Django 4.0.2 on 2022-02-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sale_cash_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.cashregister'),
        ),
    ]
