# Generated by Django 4.0.2 on 2022-02-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_sale_cash_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('open', 'Abierto'), ('pending', 'Pendiente'), ('billed', 'Depositado'), ('blocked', 'Bloqueado')], default='created', max_length=9, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='CashRegisterMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Creado'), ('open', 'Abierto'), ('pending', 'Pendiente'), ('billed', 'Depositado'), ('blocked', 'Bloqueado')], max_length=9, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.cashregister', verbose_name='Caja')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
            },
        ),
    ]
