# Generated by Django 4.0.2 on 2022-02-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_cashregister_status_cashregistermovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='amount',
        ),
    ]
