# Generated by Django 4.0.2 on 2022-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_cashregister_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('active', 'Activo'), ('disabled', 'Desactivado'), ('modified', 'Modificado')], max_length=9, verbose_name='Estado de servicio'),
        ),
    ]
