# Generated by Django 4.0.2 on 2022-02-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_cashregistermovement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestretch',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stretches', to='core.route', verbose_name='Ruta'),
        ),
    ]
