# Generated by Django 4.0.2 on 2022-02-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_routestretch_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='total_prints',
            field=models.IntegerField(verbose_name='Máxima cantidad de impresiones'),
        ),
    ]
