# Generated by Django 4.0.2 on 2022-02-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_printer_total_prints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('in', 'Ingreso'), ('out', 'Salida')], max_length=4, verbose_name='Tipo')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.cashregister', verbose_name='Caja')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Operación de caja',
                'verbose_name_plural': 'Operaciones de caja',
            },
        ),
    ]
