# Generated by Django 4.0.2 on 2022-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cashregisteroperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregisteroperation',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
