# Generated by Django 4.0.2 on 2022-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_ticket_passenger_alter_ticket_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregistermovement',
            name='voucher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voucher'),
        ),
    ]
