# Generated by Django 4.0.2 on 2022-03-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cashregistermovement_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.service', verbose_name='Servicio'),
        ),
    ]
