# Generated by Django 4.0.3 on 2022-03-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_ticket_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(blank=True, max_length=200, null=True, verbose_name='Orden compra')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='core.sale', verbose_name='Venta')),
            ],
        ),
    ]
