# Generated by Django 4.0.3 on 2022-03-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0015_personal_branch'),
        ('core', '0034_cashregisteroperation_operation_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticket', verbose_name='Autorizador')),
            ],
            options={
                'verbose_name': 'Ticket devolución',
                'verbose_name_plural': 'Tickets devolución',
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=255, verbose_name='Orden compra')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('authorized_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha autorización')),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.personal', verbose_name='Autorizador')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.sale', verbose_name='Venta')),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.refundticket', verbose_name='tickets')),
            ],
            options={
                'verbose_name': 'Solicitud de devolución',
                'verbose_name_plural': 'Solicitudes de devolución',
            },
        ),
    ]
