# Generated by Django 4.0.3 on 2022-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_refundrequest_authorizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundrequest',
            name='tickets',
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='tickets',
            field=models.ManyToManyField(blank=True, null=True, to='core.refundticket', verbose_name='tickets'),
        ),
    ]
