# Generated by Django 4.0.3 on 2022-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_refundrequest_tickets_refundrequest_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='tickets',
            field=models.ManyToManyField(to='core.refundticket', verbose_name='tickets'),
        ),
    ]
