# Generated by Django 4.0.3 on 2022-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_refundrequest_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
