# Generated by Django 4.0.3 on 2022-03-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_cashregister_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregisteroperation',
            name='linked_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cashregisteroperation', verbose_name='reference operation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('active', 'Active'), ('refunded', 'Refunded'), ('partial_refunded', 'Partial Refunded')], default='active', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='refundticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.ticket', verbose_name='Autorizador'),
        ),
    ]
