# Generated by Django 4.0.3 on 2022-04-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_cashregister_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.ticket', verbose_name='Autorizador'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tickets',
            field=models.ManyToManyField(related_name='sales', to='core.ticket', verbose_name='Boletos'),
        ),
    ]
