# Generated by Django 4.0.3 on 2022-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_refundticket_ticket_alter_sale_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='datetime_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
    ]
