# Generated by Django 4.0.3 on 2022-04-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_cashregisteroperation_linked_operation_and_more'),
        ('core', '0041_alter_service_datetime_publish'),
    ]

    operations = [
    ]
