# Generated by Django 4.0.3 on 2022-04-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_serviceseatrate_masterroutestretch_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterroutestretch',
            old_name='stretch_status',
            new_name='stretch_type',
        ),
    ]
