# Generated by Django 4.0.3 on 2022-04-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_busstop_order'),
        ('core', '0044_rename_stretch_status_masterroutestretch_stretch_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestretch',
            name='master_route_stretch',
        ),
        migrations.AddField(
            model_name='routestretch',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Distancia'),
        ),
        migrations.AddField(
            model_name='routestretch',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='routestretch',
            name='end_bus_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end_routes', to='locations.busstop', verbose_name='Parada de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestretch',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='routestretch',
            name='start_bus_stop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='start_routes', to='locations.busstop', verbose_name='Parada de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestretch',
            name='stretch_type',
            field=models.CharField(choices=[('Map', 'Mapa'), ('Stretch', 'Tramo')], default='Map', max_length=10),
        ),
        migrations.AddField(
            model_name='routestretch',
            name='waiting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tiempo de espera'),
        ),
        migrations.AlterField(
            model_name='routestretch',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.DeleteModel(
            name='RouteMap',
        ),
    ]
