# Generated by Django 4.0.3 on 2022-04-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_routestretch_master_route_stretch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestretchrate',
            name='rate_type',
        ),
    ]
