# Generated by Django 4.0.3 on 2022-04-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_refundrequest_cash_register_refundrequest_seller'),
        ('core', '0047_alter_sale_status'),
    ]

    operations = [
    ]
