# Generated by Django 4.0.3 on 2022-04-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_alter_component_polymorphic_ctype'),
        ('locations', '0007_busstop_status'),
        ('core', '0048_merge_20220411_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2048, verbose_name='Código')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('amount', 'Monto')], max_length=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo usos')),
                ('valid_until', models.DateTimeField(verbose_name='Válido hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('source', models.CharField(choices=[('web', 'Web'), ('office', 'Oficina')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('end_bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_tariff_bus_stop', to='locations.busstop', verbose_name='Parada fin')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.seattype', verbose_name='Tipo asiento')),
                ('start_bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_tariff_bus_stop', to='locations.busstop', verbose_name='Parada inicio')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
