# Generated by Django 4.0.3 on 2022-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_coupon_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='document_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de documento'),
        ),
    ]
