# Generated by Django 4.0.3 on 2022-04-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_passenger_document_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterroutestretch',
            name='end_bus_stop',
        ),
        migrations.RemoveField(
            model_name='masterroutestretch',
            name='master_route',
        ),
        migrations.RemoveField(
            model_name='masterroutestretch',
            name='start_bus_stop',
        ),
        migrations.RemoveField(
            model_name='masterroutestretchrate',
            name='master_route_stretch',
        ),
        migrations.RemoveField(
            model_name='masterroutestretchrate',
            name='seat_type',
        ),
        migrations.RemoveField(
            model_name='route',
            name='master_route',
        ),
        migrations.DeleteModel(
            name='MasterRoute',
        ),
        migrations.DeleteModel(
            name='MasterRouteStretch',
        ),
        migrations.DeleteModel(
            name='MasterRouteStretchRate',
        ),
    ]
