# Generated by Django 4.0.3 on 2022-05-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_alter_component_polymorphic_ctype'),
        ('core', '0051_remove_masterroutestretch_end_bus_stop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='seat_type',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('office', 'Oficina'), ('onway', 'En camino')], max_length=10),
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('season', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.seattype', verbose_name='Tipo de asiento')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.tariff', verbose_name='Tarifa')),
            ],
            options={
                'verbose_name': 'Tarifa por tipo de asiento',
                'verbose_name_plural': 'Tarifas por tipo de asiento',
            },
        ),
    ]
