# Generated by Django 4.0.3 on 2022-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_tariff_price_remove_tariff_seat_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='source',
        ),
        migrations.AddField(
            model_name='tariffrate',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('office', 'Oficina'), ('onway', 'En camino')], default='web', max_length=10),
        ),
    ]
