# Generated by Django 4.0.3 on 2022-05-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_tariff_source_tariffrate_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Tarifa referencial', 'verbose_name_plural': 'Tarifas referenciales'},
        ),
    ]
