# Generated by Django 4.0.3 on 2022-05-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_tariff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffrate',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('office', 'Oficina'), ('onway', 'En camino')], default='web', max_length=10, verbose_name='Fuente'),
        ),
    ]
