# Generated by Django 4.0.3 on 2022-05-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_route_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='document_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Rut'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.service', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Válido from'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Porcentaje'), ('amount', 'Monto')], default='percentage', max_length=10),
        ),
    ]
