# Generated by Django 4.0.3 on 2022-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_coupon_document_number_coupon_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='count_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Usos'),
        ),
    ]
