# Generated by Django 4.0.3 on 2022-05-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_coupon_valid_until_coupon_valid_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='service',
        ),
        migrations.AddField(
            model_name='coupon',
            name='passangers',
            field=models.ManyToManyField(related_name='coupons', to='core.passenger', verbose_name='Pasajeros'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='services',
            field=models.ManyToManyField(related_name='coupons', to='core.service', verbose_name='Servicios'),
        ),
    ]
