# Generated by Django 4.0.3 on 2022-05-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_coupon_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='document_number',
            field=models.CharField(max_length=20, verbose_name='Número de documento'),
        ),
    ]
