# Generated by Django 4.0.3 on 2022-05-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_season_stretchinfo_stretchinforate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento'),
        ),
    ]
