# Generated by Django 4.0.3 on 2022-05-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_alter_component_polymorphic_ctype'),
        ('core', '0064_ticket_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSeatRateDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=9, verbose_name='Día')),
                ('source_type', models.CharField(choices=[('web', 'Web'), ('office', 'Oficina'), ('onway', 'En camino')], default='web', max_length=20, verbose_name='Tipo de canal de venta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.seattype', verbose_name='Tipo de asiento')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_seat_rates_by_days', to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Tarifa de servicio por día',
                'verbose_name_plural': 'Tarifas de servicio por día',
            },
        ),
    ]
