# Generated by Django 4.0.3 on 2022-05-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_serviceseatrateday'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceseatrate',
            name='day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default='monday', max_length=9, verbose_name='Día'),
            preserve_default=False,
        ),
    ]
