# Generated by Django 4.0.3 on 2022-05-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_serviceseatrate_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSeatRateDay',
        ),
    ]
