# Generated by Django 4.0.3 on 2022-05-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0015_personal_branch'),
        ('locations', '0009_remove_busstop_distance_remove_busstop_duration'),
        ('core', '0067_delete_serviceseatrateday'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('amount', 'Monto')], default='percentage', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo usos')),
                ('count_uses', models.PositiveIntegerField(default=0, verbose_name='Usos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
            ],
            options={
                'verbose_name': 'Meta descuento',
                'verbose_name_plural': 'Metas descuento',
            },
        ),
        migrations.AlterField(
            model_name='serviceseatrate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.service', verbose_name='Servicio'),
        ),
        migrations.CreateModel(
            name='ServiceDiscountStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_discount', to='core.metadiscount', verbose_name='Descuento')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_discount', to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Descuento por servicio',
                'verbose_name_plural': 'Descuentos por servicio',
            },
        ),
        migrations.CreateModel(
            name='RoleDiscountStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_discount', to='core.metadiscount', verbose_name='Descuento')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_discount', to='crew.position', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Descuento por rol',
                'verbose_name_plural': 'Descuentos por rol',
            },
        ),
        migrations.CreateModel(
            name='DNIDiscountStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, verbose_name='DNI')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dni_discount', to='core.metadiscount', verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Descuento por DNI',
                'verbose_name_plural': 'Descuentos por DNI',
            },
        ),
        migrations.CreateModel(
            name='CouponDiscountStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('strategy', models.CharField(choices=[('dni', 'DNI'), ('service', 'Servicio')], default='dni', max_length=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_discount', to='core.metadiscount', verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Descuento por cupón',
                'verbose_name_plural': 'Descuentos por cupón',
            },
        ),
        migrations.CreateModel(
            name='BranchOfficeDiscountStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('dni', 'DNI'), ('service', 'Servicio')], default='dni', max_length=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido hasta')),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_office_discount', to='locations.branch', verbose_name='Sucursal')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_office_discount', to='core.metadiscount', verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Descuento por sucursal',
                'verbose_name_plural': 'Descuentos por sucursal',
            },
        ),
    ]
