# Generated by Django 4.0.3 on 2022-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_serviceseatrate_stretch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestretch',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duración'),
        ),
    ]
