# Generated by Django 4.0.3 on 2022-05-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_routestretch_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
    ]
