# Generated by Django 4.0.3 on 2022-05-25 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_service_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnidiscountstrategy',
            name='dni',
        ),
        migrations.AddField(
            model_name='coupondiscountstrategy',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='coupondiscountstrategy',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_discount', to='core.service', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='dnidiscountstrategy',
            name='rut',
            field=models.CharField(default=None, max_length=15, verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
