# Generated by Django 4.0.3 on 2022-05-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_remove_dnidiscountstrategy_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='status',
        ),
        migrations.AlterField(
            model_name='service',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.route', verbose_name='Ruta'),
        ),
    ]
