# Generated by Django 4.0.3 on 2022-06-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_route_status_alter_service_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRouteStretch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Fecha de llegada')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Hora de llegada')),
                ('route_stretch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_route_stretches', to='core.routestretch', verbose_name='Tramo de ruta')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_route_stretches', to='core.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Tramo de ruta del servicio',
                'verbose_name_plural': 'Tramos de ruta del servicio',
            },
        ),
    ]
