# Generated by Django 4.0.3 on 2022-06-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_serviceroutestretch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceroutestretch',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='serviceroutestretch',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='serviceroutestretch',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='serviceroutestretch',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='serviceroutestretch',
            name='arrival_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de llegada'),
        ),
        migrations.AddField(
            model_name='serviceroutestretch',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida'),
        ),
    ]
