# Generated by Django 4.0.3 on 2022-06-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_serviceroutestretch_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceroutestretch',
            name='arrival_datetime',
        ),
        migrations.RemoveField(
            model_name='serviceroutestretch',
            name='departure_datetime',
        ),
        migrations.AddField(
            model_name='serviceroutestretch',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de llegada'),
        ),
        migrations.AddField(
            model_name='serviceroutestretch',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
    ]
