# Generated by Django 4.0.3 on 2022-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_serviceroutestretch_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverableError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('user', models.IntegerField()),
                ('params', models.JSONField()),
                ('metadata', models.JSONField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
