# Generated by Django 4.0.3 on 2022-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_recoverableerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverableerror',
            name='code',
            field=models.TextField(),
        ),
    ]
