# Generated by Django 4.0.3 on 2022-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_recoverableerror_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverableerror',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
