# Generated by Django 4.0.5 on 2022-06-29 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_remove_busstop_distance_remove_busstop_duration'),
        ('core', '0080_alter_recoverableerror_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='locations.branch', verbose_name='Sucursal'),
        ),
    ]
