# Generated by Django 4.0.5 on 2022-06-29 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_cashregister_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='passangers',
        ),
    ]
