# Generated by Django 4.0.5 on 2022-06-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_coupon_passangers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
    ]
