# Generated by Django 4.0.5 on 2022-06-29 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0083_remove_ticket_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='phone',
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
