# Generated by Django 4.0.5 on 2022-06-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_data_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='passangers',
            field=models.ManyToManyField(related_name='coupons', to='core.passenger', verbose_name='Pasajeros'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.passenger', verbose_name='Pasajero'),
            preserve_default=False,
        ),
    ]
