# Generated by Django 4.0.5 on 2022-08-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0017_alter_personal_contract_type'),
        ('core', '0086_ticket_end_bus_stop_ticket_start_bus_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crew.personal', verbose_name='Personal')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.service', verbose_name='Servicio')),
            ],
        ),
    ]
