# Generated by Django 4.0.5 on 2022-09-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_servicemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
    ]
